version: '3.7'

services:
  node:
    image: node:18.0.0-alpine
    user: node
    tty: true
    stdin_open: true
    entrypoint: node
    working_dir: /home/node
    ports:
      - ${PORT_CLIENT-8000}:${PORT_CLIENT-8000}
    volumes:
      - .:/home/node
