version: '3.7'

services:
  node:
    image: node:18.0.0-alpine
    user: node
    tty: true
    stdin_open: true
    entrypoint: node
    working_dir: /home/node
    networks:
      - e2e
    ports:
      - 3000:3000
      - 5111:5111
    volumes:
      - .:/home/node

networks:
  e2e:
    external: true