version: '3.7'

services:
  node:
    container_name: node
    image: node:18.0.0-alpine
    user: node
    tty: true
    stdin_open: true
    entrypoint: node
    working_dir: /home/node
    ports:
      - 3000:3000
      - 5111:5111
    volumes:
      - .:/home/node
