name: deploy
on:
  push:
    branches:
      - main
    
jobs:
  update:
    name: Updating repo
    runs-on: ubuntu-latest
    steps:
      - name: updating repo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PWD }}
          script: |
            cd ChallengeS1
            git pull

  install:
    name: Installing new packages
    runs-on: ubuntu-latest
    steps:
      - name: Installing packages
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PWD }}
          script: |
            cd ChallengeS1/vue-app
            docker compose down
            docker compose up -d
            docker compose exec node npm install
    needs: update

  run:
    name: Executing app
    runs-on: ubuntu-latest
    steps:
      - name: Executing app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PWD }}
          script: |
            cd ChallengeS1/vue-app
            docker compose exec -d node npm run dev
    needs: install