name: deploy
on:
  push:
    branches:
      - deploy
    
jobs:
  update:
    name: Updating repo
    runs-on: ubuntu-latest
    steps:
      - name: updating repo
        uses: appleboy/ssh-action@master
        with:
          host: '82.66.178.56'
          username: 'loxs'
          password: 'locman123-'
          script: |
            cd ChallengeS1
            git pull
            
  install:
    name: Installing new packages
    runs-on: ubuntu-latest
    steps:
      - name: Installing packages
        uses: appleboy/ssh-action@master
        with:
          host: '82.66.178.56'
          username: 'loxs'
          password: 'locman123-'
          script: |
            cd ChallengeS1/vue-app
            docker compose exec node npm install
            
  run:
    name: Executing app
    runs-on: ubuntu-latest
    steps:
      - name: Executing app
        uses: appleboy/ssh-action@master
        with:
          host: '82.66.178.56'
          username: 'loxs'
          password: 'locman123-'
          script: |
            cd ChallengeS1/vue-app
            docker compose exec node npm run dev